// const {emailTemplate} = require('./js-foundation/01-template')
// require('./js-foundation/02-destructuring')
// require('./js-foundation/03-callbacks')
// require('./js-foundation/04-callbacks-arrow')
// require('./js-foundation/05-factory')
// require('./js-foundation/06-promises')
require('./js-foundation/06-promises-adapter')
